CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          category_name VARCHAR(255) NOT NULL
);

CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         description VARCHAR(255),
                         price NUMERIC(38,2) NOT NULL,
                         category_id BIGINT,
                         stock INTEGER,
                         creation_date TIMESTAMP(6),
                         last_update_date TIMESTAMP(6)
);

ALTER TABLE product ADD CONSTRAINT FK_product_category_id FOREIGN KEY (category_id) REFERENCES category (id);